# Generated by Django 5.2 on 2025-05-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('apogee', models.FloatField(blank=True, null=True)),
                ('inclination', models.FloatField()),
                ('heading', models.FloatField()),
                ('rail_length', models.FloatField()),
                ('cansat_mass', models.FloatField()),
                ('drag_coeff', models.FloatField()),
                ('burn_time', models.FloatField()),
                ('avg_thrust', models.FloatField()),
                ('elevation', models.FloatField()),
            ],
        ),
    ]
